import { DataStructure } from "./datastructure";

export const DATASTRUCTURELIST: DataStructure[] = [
    {
      name: 'Array',
      ac_search: 'O(n)',
      ac_insert: 'N/A',
      ac_delete: 'N/A',
      wc_search: 'O(n)',
      wc_insert: 'N/A',
      wc_delete: 'N/A',
    },
    {
      name: 'Sorted Array',
      ac_search: 'O(n log n)',
      ac_insert: 'O(n)',
      ac_delete: 'O(n)',
      wc_search: 'O(n log n)',
      wc_insert: 'O(n)',
      wc_delete: 'O(n)',
    },
    {
      name: 'Linked List',
      ac_search: 'O(n)',
      ac_insert: 'O(1)',
      ac_delete: 'O(1)',
      wc_search: 'O(n)',
      wc_insert: 'O(1)',
      wc_delete: 'O(1)',
    },
    {
      name: 'Doubly Linked List',
      ac_search: 'O(n)',
      ac_insert: 'O(1)',
      ac_delete: 'O(1)',
      wc_search: 'O(n)',
      wc_insert: 'O(1)',
      wc_delete: 'O(1)',
    },
    {
      name: 'Stack',
      ac_search: 'O(n)',
      ac_insert: 'O(1)',
      ac_delete: 'O(1)',
      wc_search: 'O(n)',
      wc_insert: 'O(1)',
      wc_delete: 'O(1)',
    },
    {
      name: 'Hash Table',
      ac_search: 'O(1)',
      ac_insert: 'O(1)',
      ac_delete: 'O(1)',
      wc_search: 'O(n)',
      wc_insert: 'O(n)',
      wc_delete: 'O(n)',
    },
    {
      name: 'Binary Search Tree',
      ac_search: 'O(log n)',
      ac_insert: 'O(log n)',
      ac_delete: 'O(log n)',
      wc_search: 'O(n)',
      wc_insert: 'O(n)',
      wc_delete: 'O(n)',
    },
    {
      name: 'B-Tree',
      ac_search: 'O(log n)',
      ac_insert: 'O(log n)',
      ac_delete: 'O(log n)',
      wc_search: 'O(log n)',
      wc_insert: 'O(log n)',
      wc_delete: 'O(log n)',
    },
    {
      name: 'Red Black Tree',
      ac_search: 'O(log n)',
      ac_insert: 'O(log n)',
      ac_delete: 'O(log n)',
      wc_search: 'O(log n)',
      wc_insert: 'O(log n)',
      wc_delete: 'O(log n)',
    },
    {
      name: 'AVL Tree',
      ac_search: 'O(log n)',
      ac_insert: 'O(log n)',
      ac_delete: 'O(log n)',
      wc_search: 'O(log n)',
      wc_insert: 'O(log n)',
      wc_delete: 'O(log n)',
    }
  ];